// controllers/cardController.js
// TODO: Connect database queries and AI prompts engine (e.g. Gemini, OpenAI, DALL-E)

export const getTemplates = async (req, res) => {
  console.log("🎨 [CARDS] Fetching default greeting card templates");

  const mockTemplates = [
    { id: "tpl-1", title: "Cyberpunk Birthday", occasion: "Birthday", theme: "Neon" },
    { id: "tpl-2", title: "Glass Anniversary", occasion: "Anniversary", theme: "Glass" },
    { id: "tpl-3", title: "Golden Luxury Thanks", occasion: "Thank You", theme: "Luxury" },
  ];

  return res.status(200).json({
    success: true,
    templates: mockTemplates,
  });
};

export const generateCard = async (req, res) => {
  const { prompt, occasion, theme } = req.body;
  console.log(`🎨 [CARDS] Requesting AI generation: Occasion=${occasion}, Theme=${theme}, Prompt="${prompt}"`);

  if (!prompt) {
    return res.status(400).json({
      success: false,
      message: "Please enter a descriptive prompt for AI generation",
    });
  }

  // Simulate prompt completion returning dummy card layout metadata
  return res.status(200).json({
    success: true,
    message: "Card generated successfully (mock)",
    generatedCard: {
      id: "card-" + Math.floor(Math.random() * 1000),
      title: `AI Generated ${occasion}`,
      prompt: prompt,
      occasion: occasion,
      theme: theme,
      gradient: "from-purple-900 via-pink-700 to-cyan-500",
      description: `"${prompt}" — custom greeting generated by Blink AI engine.`,
      author: "Blink AI",
      createdAt: new Date().toISOString(),
    },
  });
};
